### ISSUE TITLE
undefined symbol: glBegin

### ISSUE THREAD

**Issue by tsmaster** [TomoshibiAkira/PyPGE#1]
On Ubuntu Linux, I cloned and installed with Python 3.8. When running any of the examples, I get an error:

Traceback (most recent call last):
  File "breakout.py", line 1, in <module>
    import PyPGE as PGE
ImportError: /home/tsmaster/.local/lib/python3.8/site-packages/PyPGE.cpython-38-x86_64-linux-gnu.so: undefined symbol: glBegin

Maybe pybind needs to know to link to OpenGL?

**Comment by TomoshibiAkira** [comment]
Thanks for the report! I didn't try building on a Ubuntu machine last time.
The updated `setup.py` should be working fine (tested on an 18.04 VM).

**Comment by tsmaster** [comment]
Great, thanks!
